// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BackForthController from "./back_forth_controller"
application.register("back-forth", BackForthController)

import BigmapController from "./bigmap_controller"
application.register("bigmap", BigmapController)

import FullscreenController from "./fullscreen_controller"
application.register("fullscreen", FullscreenController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LinkHelperController from "./link_helper_controller"
application.register("link-helper", LinkHelperController)

import MapController from "./map_controller"
application.register("map", MapController)

import OrientController from "./orient_controller"
application.register("orient", OrientController)

import OverflowController from "./overflow_controller"
application.register("overflow", OverflowController)

import PagerController from "./pager_controller"
application.register("pager", PagerController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import WorldmapController from "./worldmap_controller"
application.register("worldmap", WorldmapController)
