// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LinkHelperController from "./link_helper_controller"
application.register("link-helper", LinkHelperController)

import MapController from "./map_controller"
application.register("map", MapController)

import OrientController from "./orient_controller"
application.register("orient", OrientController)
